matUtils extract -i publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.pb -s BATCH_SAMPLES/1_samples.txt -v BATCH_VCFs/1_samples.vcf
matUtils extract -i publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.pb -s BATCH_SAMPLES/2_samples.txt -v BATCH_VCFs/2_samples.vcf
matUtils extract -i publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.pb -s BATCH_SAMPLES/3_samples.txt -v BATCH_VCFs/3_samples.vcf
matUtils extract -i publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.pb -s BATCH_SAMPLES/4_samples.txt -v BATCH_VCFs/4_samples.vcf
matUtils extract -i publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.pb -s BATCH_SAMPLES/5_samples.txt -v BATCH_VCFs/5_samples.vcf
matUtils extract -i publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.pb -s BATCH_SAMPLES/6_samples.txt -v BATCH_VCFs/6_samples.vcf
matUtils extract -i publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.pb -s BATCH_SAMPLES/7_samples.txt -v BATCH_VCFs/7_samples.vcf
matUtils extract -i publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.pb -s BATCH_SAMPLES/8_samples.txt -v BATCH_VCFs/8_samples.vcf
matUtils extract -i publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.pb -s BATCH_SAMPLES/9_samples.txt -v BATCH_VCFs/9_samples.vcf
matUtils extract -i publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.pb -s BATCH_SAMPLES/10_samples.txt -v BATCH_VCFs/10_samples.vcf
matUtils extract -i publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.pb -s BATCH_SAMPLES/11_samples.txt -v BATCH_VCFs/11_samples.vcf
matUtils extract -i publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.pb -s BATCH_SAMPLES/12_samples.txt -v BATCH_VCFs/12_samples.vcf
matUtils extract -i publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.pb -s BATCH_SAMPLES/13_samples.txt -v BATCH_VCFs/13_samples.vcf
matUtils extract -i publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.pb -s BATCH_SAMPLES/14_samples.txt -v BATCH_VCFs/14_samples.vcf
matUtils extract -i publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.pb -s BATCH_SAMPLES/15_samples.txt -v BATCH_VCFs/15_samples.vcf
matUtils extract -i publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.pb -s BATCH_SAMPLES/16_samples.txt -v BATCH_VCFs/16_samples.vcf
matUtils extract -i publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.pb -s BATCH_SAMPLES/17_samples.txt -v BATCH_VCFs/17_samples.vcf
matUtils extract -i publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.pb -s BATCH_SAMPLES/18_samples.txt -v BATCH_VCFs/18_samples.vcf
matUtils extract -i publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.pb -s BATCH_SAMPLES/19_samples.txt -v BATCH_VCFs/19_samples.vcf
matUtils extract -i publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.pb -s BATCH_SAMPLES/20_samples.txt -v BATCH_VCFs/20_samples.vcf
matUtils extract -i publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.pb -s BATCH_SAMPLES/21_samples.txt -v BATCH_VCFs/21_samples.vcf
matUtils extract -i publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.pb -s BATCH_SAMPLES/22_samples.txt -v BATCH_VCFs/22_samples.vcf
matUtils extract -i publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.pb -s BATCH_SAMPLES/23_samples.txt -v BATCH_VCFs/23_samples.vcf
matUtils extract -i publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.pb -s BATCH_SAMPLES/24_samples.txt -v BATCH_VCFs/24_samples.vcf
matUtils extract -i publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.pb -s BATCH_SAMPLES/25_samples.txt -v BATCH_VCFs/25_samples.vcf
matUtils extract -i publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.pb -s BATCH_SAMPLES/26_samples.txt -v BATCH_VCFs/26_samples.vcf
matUtils extract -i publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.pb -s BATCH_SAMPLES/27_samples.txt -v BATCH_VCFs/27_samples.vcf
matUtils extract -i publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.pb -s BATCH_SAMPLES/28_samples.txt -v BATCH_VCFs/28_samples.vcf
matUtils extract -i publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.pb -s BATCH_SAMPLES/29_samples.txt -v BATCH_VCFs/29_samples.vcf
matUtils extract -i publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.pb -s BATCH_SAMPLES/30_samples.txt -v BATCH_VCFs/30_samples.vcf
matUtils extract -i publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.pb -s BATCH_SAMPLES/31_samples.txt -v BATCH_VCFs/31_samples.vcf
matUtils extract -i publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.pb -s BATCH_SAMPLES/32_samples.txt -v BATCH_VCFs/32_samples.vcf
matUtils extract -i publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.pb -s BATCH_SAMPLES/33_samples.txt -v BATCH_VCFs/33_samples.vcf
matUtils extract -i publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.pb -s BATCH_SAMPLES/34_samples.txt -v BATCH_VCFs/34_samples.vcf
matUtils extract -i publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.pb -s BATCH_SAMPLES/35_samples.txt -v BATCH_VCFs/35_samples.vcf
matUtils extract -i publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.pb -s BATCH_SAMPLES/36_samples.txt -v BATCH_VCFs/36_samples.vcf
matUtils extract -i publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.pb -s BATCH_SAMPLES/37_samples.txt -v BATCH_VCFs/37_samples.vcf
matUtils extract -i publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.pb -s BATCH_SAMPLES/38_samples.txt -v BATCH_VCFs/38_samples.vcf
matUtils extract -i publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.pb -s BATCH_SAMPLES/39_samples.txt -v BATCH_VCFs/39_samples.vcf
matUtils extract -i publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.pb -s BATCH_SAMPLES/40_samples.txt -v BATCH_VCFs/40_samples.vcf
matUtils extract -i publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.pb -s BATCH_SAMPLES/41_samples.txt -v BATCH_VCFs/41_samples.vcf
matUtils extract -i publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.pb -s BATCH_SAMPLES/42_samples.txt -v BATCH_VCFs/42_samples.vcf
matUtils extract -i publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.pb -s BATCH_SAMPLES/43_samples.txt -v BATCH_VCFs/43_samples.vcf
matUtils extract -i publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.pb -s BATCH_SAMPLES/44_samples.txt -v BATCH_VCFs/44_samples.vcf
matUtils extract -i publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.pb -s BATCH_SAMPLES/45_samples.txt -v BATCH_VCFs/45_samples.vcf
matUtils extract -i publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.pb -s BATCH_SAMPLES/46_samples.txt -v BATCH_VCFs/46_samples.vcf
matUtils extract -i publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.pb -s BATCH_SAMPLES/47_samples.txt -v BATCH_VCFs/47_samples.vcf
matUtils extract -i publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.pb -s BATCH_SAMPLES/48_samples.txt -v BATCH_VCFs/48_samples.vcf
matUtils extract -i publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.pb -s BATCH_SAMPLES/49_samples.txt -v BATCH_VCFs/49_samples.vcf
matUtils extract -i publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.pb -s BATCH_SAMPLES/50_samples.txt -v BATCH_VCFs/50_samples.vcf
matUtils extract -i publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.pb -s BATCH_SAMPLES/51_samples.txt -v BATCH_VCFs/51_samples.vcf
matUtils extract -i publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.pb -s BATCH_SAMPLES/52_samples.txt -v BATCH_VCFs/52_samples.vcf
matUtils extract -i publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.pb -s BATCH_SAMPLES/53_samples.txt -v BATCH_VCFs/53_samples.vcf
matUtils extract -i publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.pb -s BATCH_SAMPLES/54_samples.txt -v BATCH_VCFs/54_samples.vcf
matUtils extract -i publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.pb -s BATCH_SAMPLES/55_samples.txt -v BATCH_VCFs/55_samples.vcf
matUtils extract -i publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.pb -s BATCH_SAMPLES/56_samples.txt -v BATCH_VCFs/56_samples.vcf
matUtils extract -i publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.pb -s BATCH_SAMPLES/57_samples.txt -v BATCH_VCFs/57_samples.vcf
matUtils extract -i publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.pb -s BATCH_SAMPLES/58_samples.txt -v BATCH_VCFs/58_samples.vcf
matUtils extract -i publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.pb -s BATCH_SAMPLES/59_samples.txt -v BATCH_VCFs/59_samples.vcf
matUtils extract -i publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.pb -s BATCH_SAMPLES/60_samples.txt -v BATCH_VCFs/60_samples.vcf
matUtils extract -i publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.pb -s BATCH_SAMPLES/61_samples.txt -v BATCH_VCFs/61_samples.vcf
matUtils extract -i publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.pb -s BATCH_SAMPLES/62_samples.txt -v BATCH_VCFs/62_samples.vcf
matUtils extract -i publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.pb -s BATCH_SAMPLES/63_samples.txt -v BATCH_VCFs/63_samples.vcf
matUtils extract -i publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.pb -s BATCH_SAMPLES/64_samples.txt -v BATCH_VCFs/64_samples.vcf
matUtils extract -i publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.pb -s BATCH_SAMPLES/65_samples.txt -v BATCH_VCFs/65_samples.vcf
matUtils extract -i publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.pb -s BATCH_SAMPLES/66_samples.txt -v BATCH_VCFs/66_samples.vcf
matUtils extract -i publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.pb -s BATCH_SAMPLES/67_samples.txt -v BATCH_VCFs/67_samples.vcf
matUtils extract -i publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.pb -s BATCH_SAMPLES/68_samples.txt -v BATCH_VCFs/68_samples.vcf
matUtils extract -i publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.pb -s BATCH_SAMPLES/69_samples.txt -v BATCH_VCFs/69_samples.vcf
matUtils extract -i publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.pb -s BATCH_SAMPLES/70_samples.txt -v BATCH_VCFs/70_samples.vcf
matUtils extract -i publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.pb -s BATCH_SAMPLES/71_samples.txt -v BATCH_VCFs/71_samples.vcf
matUtils extract -i publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.pb -s BATCH_SAMPLES/72_samples.txt -v BATCH_VCFs/72_samples.vcf
matUtils extract -i publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.pb -s BATCH_SAMPLES/73_samples.txt -v BATCH_VCFs/73_samples.vcf
matUtils extract -i publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.pb -s BATCH_SAMPLES/74_samples.txt -v BATCH_VCFs/74_samples.vcf
matUtils extract -i publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.pb -s BATCH_SAMPLES/75_samples.txt -v BATCH_VCFs/75_samples.vcf
