cat 1_*.fasta > COMBINED_FASTAS/1.fasta
cat 2_*.fasta > COMBINED_FASTAS/2.fasta
cat 3_*.fasta > COMBINED_FASTAS/3.fasta
cat 4_*.fasta > COMBINED_FASTAS/4.fasta
cat 5_*.fasta > COMBINED_FASTAS/5.fasta
cat 6_*.fasta > COMBINED_FASTAS/6.fasta
cat 7_*.fasta > COMBINED_FASTAS/7.fasta
cat 8_*.fasta > COMBINED_FASTAS/8.fasta
cat 9_*.fasta > COMBINED_FASTAS/9.fasta
cat 10_*.fasta > COMBINED_FASTAS/10.fasta
cat 11_*.fasta > COMBINED_FASTAS/11.fasta
cat 12_*.fasta > COMBINED_FASTAS/12.fasta
cat 13_*.fasta > COMBINED_FASTAS/13.fasta
cat 14_*.fasta > COMBINED_FASTAS/14.fasta
cat 15_*.fasta > COMBINED_FASTAS/15.fasta
cat 16_*.fasta > COMBINED_FASTAS/16.fasta
cat 17_*.fasta > COMBINED_FASTAS/17.fasta
cat 18_*.fasta > COMBINED_FASTAS/18.fasta
cat 19_*.fasta > COMBINED_FASTAS/19.fasta
cat 20_*.fasta > COMBINED_FASTAS/20.fasta
cat 21_*.fasta > COMBINED_FASTAS/21.fasta
cat 22_*.fasta > COMBINED_FASTAS/22.fasta
cat 23_*.fasta > COMBINED_FASTAS/23.fasta
cat 24_*.fasta > COMBINED_FASTAS/24.fasta
cat 25_*.fasta > COMBINED_FASTAS/25.fasta
cat 26_*.fasta > COMBINED_FASTAS/26.fasta
cat 27_*.fasta > COMBINED_FASTAS/27.fasta
cat 28_*.fasta > COMBINED_FASTAS/28.fasta
cat 29_*.fasta > COMBINED_FASTAS/29.fasta
cat 30_*.fasta > COMBINED_FASTAS/30.fasta
cat 31_*.fasta > COMBINED_FASTAS/31.fasta
cat 32_*.fasta > COMBINED_FASTAS/32.fasta
cat 33_*.fasta > COMBINED_FASTAS/33.fasta
cat 34_*.fasta > COMBINED_FASTAS/34.fasta
cat 35_*.fasta > COMBINED_FASTAS/35.fasta
cat 36_*.fasta > COMBINED_FASTAS/36.fasta
cat 37_*.fasta > COMBINED_FASTAS/37.fasta
cat 38_*.fasta > COMBINED_FASTAS/38.fasta
cat 39_*.fasta > COMBINED_FASTAS/39.fasta
cat 40_*.fasta > COMBINED_FASTAS/40.fasta
cat 41_*.fasta > COMBINED_FASTAS/41.fasta
cat 42_*.fasta > COMBINED_FASTAS/42.fasta
cat 43_*.fasta > COMBINED_FASTAS/43.fasta
cat 44_*.fasta > COMBINED_FASTAS/44.fasta
cat 45_*.fasta > COMBINED_FASTAS/45.fasta
cat 46_*.fasta > COMBINED_FASTAS/46.fasta
cat 47_*.fasta > COMBINED_FASTAS/47.fasta
cat 48_*.fasta > COMBINED_FASTAS/48.fasta
cat 49_*.fasta > COMBINED_FASTAS/49.fasta
cat 50_*.fasta > COMBINED_FASTAS/50.fasta
