matUtils summary -i 1_samples.opt.pb -s SAMPLES_LISTS/1_samples.samples_list.txt -T 10
matUtils summary -i 2_samples.opt.pb -s SAMPLES_LISTS/2_samples.samples_list.txt -T 10
matUtils summary -i 3_samples.opt.pb -s SAMPLES_LISTS/3_samples.samples_list.txt -T 10
matUtils summary -i 4_samples.opt.pb -s SAMPLES_LISTS/4_samples.samples_list.txt -T 10
matUtils summary -i 5_samples.opt.pb -s SAMPLES_LISTS/5_samples.samples_list.txt -T 10
matUtils summary -i 6_samples.opt.pb -s SAMPLES_LISTS/6_samples.samples_list.txt -T 10
matUtils summary -i 7_samples.opt.pb -s SAMPLES_LISTS/7_samples.samples_list.txt -T 10
matUtils summary -i 8_samples.opt.pb -s SAMPLES_LISTS/8_samples.samples_list.txt -T 10
matUtils summary -i 9_samples.opt.pb -s SAMPLES_LISTS/9_samples.samples_list.txt -T 10
matUtils summary -i 10_samples.opt.pb -s SAMPLES_LISTS/10_samples.samples_list.txt -T 10
matUtils summary -i 11_samples.opt.pb -s SAMPLES_LISTS/11_samples.samples_list.txt -T 10
matUtils summary -i 12_samples.opt.pb -s SAMPLES_LISTS/12_samples.samples_list.txt -T 10
matUtils summary -i 13_samples.opt.pb -s SAMPLES_LISTS/13_samples.samples_list.txt -T 10
matUtils summary -i 14_samples.opt.pb -s SAMPLES_LISTS/14_samples.samples_list.txt -T 10
matUtils summary -i 15_samples.opt.pb -s SAMPLES_LISTS/15_samples.samples_list.txt -T 10
matUtils summary -i 16_samples.opt.pb -s SAMPLES_LISTS/16_samples.samples_list.txt -T 10
matUtils summary -i 17_samples.opt.pb -s SAMPLES_LISTS/17_samples.samples_list.txt -T 10
matUtils summary -i 18_samples.opt.pb -s SAMPLES_LISTS/18_samples.samples_list.txt -T 10
matUtils summary -i 19_samples.opt.pb -s SAMPLES_LISTS/19_samples.samples_list.txt -T 10
matUtils summary -i 20_samples.opt.pb -s SAMPLES_LISTS/20_samples.samples_list.txt -T 10
matUtils summary -i 21_samples.opt.pb -s SAMPLES_LISTS/21_samples.samples_list.txt -T 10
matUtils summary -i 22_samples.opt.pb -s SAMPLES_LISTS/22_samples.samples_list.txt -T 10
matUtils summary -i 23_samples.opt.pb -s SAMPLES_LISTS/23_samples.samples_list.txt -T 10
matUtils summary -i 24_samples.opt.pb -s SAMPLES_LISTS/24_samples.samples_list.txt -T 10
matUtils summary -i 25_samples.opt.pb -s SAMPLES_LISTS/25_samples.samples_list.txt -T 10
matUtils summary -i 26_samples.opt.pb -s SAMPLES_LISTS/26_samples.samples_list.txt -T 10
matUtils summary -i 27_samples.opt.pb -s SAMPLES_LISTS/27_samples.samples_list.txt -T 10
matUtils summary -i 28_samples.opt.pb -s SAMPLES_LISTS/28_samples.samples_list.txt -T 10
matUtils summary -i 29_samples.opt.pb -s SAMPLES_LISTS/29_samples.samples_list.txt -T 10
matUtils summary -i 30_samples.opt.pb -s SAMPLES_LISTS/30_samples.samples_list.txt -T 10
matUtils summary -i 31_samples.opt.pb -s SAMPLES_LISTS/31_samples.samples_list.txt -T 10
matUtils summary -i 32_samples.opt.pb -s SAMPLES_LISTS/32_samples.samples_list.txt -T 10
matUtils summary -i 33_samples.opt.pb -s SAMPLES_LISTS/33_samples.samples_list.txt -T 10
matUtils summary -i 34_samples.opt.pb -s SAMPLES_LISTS/34_samples.samples_list.txt -T 10
matUtils summary -i 35_samples.opt.pb -s SAMPLES_LISTS/35_samples.samples_list.txt -T 10
matUtils summary -i 36_samples.opt.pb -s SAMPLES_LISTS/36_samples.samples_list.txt -T 10
matUtils summary -i 37_samples.opt.pb -s SAMPLES_LISTS/37_samples.samples_list.txt -T 10
matUtils summary -i 38_samples.opt.pb -s SAMPLES_LISTS/38_samples.samples_list.txt -T 10
matUtils summary -i 39_samples.opt.pb -s SAMPLES_LISTS/39_samples.samples_list.txt -T 10
matUtils summary -i 40_samples.opt.pb -s SAMPLES_LISTS/40_samples.samples_list.txt -T 10
matUtils summary -i 41_samples.opt.pb -s SAMPLES_LISTS/41_samples.samples_list.txt -T 10
matUtils summary -i 42_samples.opt.pb -s SAMPLES_LISTS/42_samples.samples_list.txt -T 10
matUtils summary -i 43_samples.opt.pb -s SAMPLES_LISTS/43_samples.samples_list.txt -T 10
matUtils summary -i 44_samples.opt.pb -s SAMPLES_LISTS/44_samples.samples_list.txt -T 10
matUtils summary -i 45_samples.opt.pb -s SAMPLES_LISTS/45_samples.samples_list.txt -T 10
matUtils summary -i 46_samples.opt.pb -s SAMPLES_LISTS/46_samples.samples_list.txt -T 10
matUtils summary -i 47_samples.opt.pb -s SAMPLES_LISTS/47_samples.samples_list.txt -T 10
matUtils summary -i 48_samples.opt.pb -s SAMPLES_LISTS/48_samples.samples_list.txt -T 10
matUtils summary -i 49_samples.opt.pb -s SAMPLES_LISTS/49_samples.samples_list.txt -T 10
matUtils summary -i 50_samples.opt.pb -s SAMPLES_LISTS/50_samples.samples_list.txt -T 10
