# java -jar /mnt/TreeCmp_v2.0-b76/bin/treeCmp.jar -r MATOPT/publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.collapsed.1_samples.nwk -d rf mc tt ms -i MATOPT/1_samples.opt.pb.nwk -o MATOPT_TREECMP_RESULTS/1_samples.opt.results
# java -jar /mnt/TreeCmp_v2.0-b76/bin/treeCmp.jar -r MATOPT/publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.collapsed.2_samples.nwk -d rf mc tt ms -i MATOPT/2_samples.opt.pb.nwk -o MATOPT_TREECMP_RESULTS/2_samples.opt.results
# java -jar /mnt/TreeCmp_v2.0-b76/bin/treeCmp.jar -r MATOPT/publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.collapsed.3_samples.nwk -d rf mc tt ms -i MATOPT/3_samples.opt.pb.nwk -o MATOPT_TREECMP_RESULTS/3_samples.opt.results
# java -jar /mnt/TreeCmp_v2.0-b76/bin/treeCmp.jar -r MATOPT/publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.collapsed.4_samples.nwk -d rf mc tt ms -i MATOPT/4_samples.opt.pb.nwk -o MATOPT_TREECMP_RESULTS/4_samples.opt.results
# java -jar /mnt/TreeCmp_v2.0-b76/bin/treeCmp.jar -r MATOPT/publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.collapsed.5_samples.nwk -d rf mc tt ms -i MATOPT/5_samples.opt.pb.nwk -o MATOPT_TREECMP_RESULTS/5_samples.opt.results
# java -jar /mnt/TreeCmp_v2.0-b76/bin/treeCmp.jar -r MATOPT/publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.collapsed.6_samples.nwk -d rf mc tt ms -i MATOPT/6_samples.opt.pb.nwk -o MATOPT_TREECMP_RESULTS/6_samples.opt.results
# java -jar /mnt/TreeCmp_v2.0-b76/bin/treeCmp.jar -r MATOPT/publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.collapsed.7_samples.nwk -d rf mc tt ms -i MATOPT/7_samples.opt.pb.nwk -o MATOPT_TREECMP_RESULTS/7_samples.opt.results
# java -jar /mnt/TreeCmp_v2.0-b76/bin/treeCmp.jar -r MATOPT/publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.collapsed.8_samples.nwk -d rf mc tt ms -i MATOPT/8_samples.opt.pb.nwk -o MATOPT_TREECMP_RESULTS/8_samples.opt.results
# java -jar /mnt/TreeCmp_v2.0-b76/bin/treeCmp.jar -r MATOPT/publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.collapsed.9_samples.nwk -d rf mc tt ms -i MATOPT/9_samples.opt.pb.nwk -o MATOPT_TREECMP_RESULTS/9_samples.opt.results
# java -jar /mnt/TreeCmp_v2.0-b76/bin/treeCmp.jar -r MATOPT/publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.collapsed.10_samples.nwk -d rf mc tt ms -i MATOPT/10_samples.opt.pb.nwk -o MATOPT_TREECMP_RESULTS/10_samples.opt.results
# java -jar /mnt/TreeCmp_v2.0-b76/bin/treeCmp.jar -r MATOPT/publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.collapsed.11_samples.nwk -d rf mc tt ms -i MATOPT/11_samples.opt.pb.nwk -o MATOPT_TREECMP_RESULTS/11_samples.opt.results
# java -jar /mnt/TreeCmp_v2.0-b76/bin/treeCmp.jar -r MATOPT/publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.collapsed.12_samples.nwk -d rf mc tt ms -i MATOPT/12_samples.opt.pb.nwk -o MATOPT_TREECMP_RESULTS/12_samples.opt.results
# java -jar /mnt/TreeCmp_v2.0-b76/bin/treeCmp.jar -r MATOPT/publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.collapsed.13_samples.nwk -d rf mc tt ms -i MATOPT/13_samples.opt.pb.nwk -o MATOPT_TREECMP_RESULTS/13_samples.opt.results
# java -jar /mnt/TreeCmp_v2.0-b76/bin/treeCmp.jar -r MATOPT/publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.collapsed.14_samples.nwk -d rf mc tt ms -i MATOPT/14_samples.opt.pb.nwk -o MATOPT_TREECMP_RESULTS/14_samples.opt.results
# java -jar /mnt/TreeCmp_v2.0-b76/bin/treeCmp.jar -r MATOPT/publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.collapsed.15_samples.nwk -d rf mc tt ms -i MATOPT/15_samples.opt.pb.nwk -o MATOPT_TREECMP_RESULTS/15_samples.opt.results
# java -jar /mnt/TreeCmp_v2.0-b76/bin/treeCmp.jar -r MATOPT/publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.collapsed.16_samples.nwk -d rf mc tt ms -i MATOPT/16_samples.opt.pb.nwk -o MATOPT_TREECMP_RESULTS/16_samples.opt.results
# java -jar /mnt/TreeCmp_v2.0-b76/bin/treeCmp.jar -r MATOPT/publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.collapsed.17_samples.nwk -d rf mc tt ms -i MATOPT/17_samples.opt.pb.nwk -o MATOPT_TREECMP_RESULTS/17_samples.opt.results
# java -jar /mnt/TreeCmp_v2.0-b76/bin/treeCmp.jar -r MATOPT/publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.collapsed.18_samples.nwk -d rf mc tt ms -i MATOPT/18_samples.opt.pb.nwk -o MATOPT_TREECMP_RESULTS/18_samples.opt.results
# java -jar /mnt/TreeCmp_v2.0-b76/bin/treeCmp.jar -r MATOPT/publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.collapsed.19_samples.nwk -d rf mc tt ms -i MATOPT/19_samples.opt.pb.nwk -o MATOPT_TREECMP_RESULTS/19_samples.opt.results
java -jar /mnt/TreeCmp_v2.0-b76/bin/treeCmp.jar -r MATOPT/publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.collapsed.20_samples.nwk -d rf mc tt ms -i MATOPT/20_samples.opt.pb.nwk -o MATOPT_TREECMP_RESULTS/20_samples.opt.results
java -jar /mnt/TreeCmp_v2.0-b76/bin/treeCmp.jar -r MATOPT/publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.collapsed.21_samples.nwk -d rf mc tt ms -i MATOPT/21_samples.opt.pb.nwk -o MATOPT_TREECMP_RESULTS/21_samples.opt.results
java -jar /mnt/TreeCmp_v2.0-b76/bin/treeCmp.jar -r MATOPT/publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.collapsed.22_samples.nwk -d rf mc tt ms -i MATOPT/22_samples.opt.pb.nwk -o MATOPT_TREECMP_RESULTS/22_samples.opt.results
java -jar /mnt/TreeCmp_v2.0-b76/bin/treeCmp.jar -r MATOPT/publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.collapsed.23_samples.nwk -d rf mc tt ms -i MATOPT/23_samples.opt.pb.nwk -o MATOPT_TREECMP_RESULTS/23_samples.opt.results
java -jar /mnt/TreeCmp_v2.0-b76/bin/treeCmp.jar -r MATOPT/publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.collapsed.24_samples.nwk -d rf mc tt ms -i MATOPT/24_samples.opt.pb.nwk -o MATOPT_TREECMP_RESULTS/24_samples.opt.results
java -jar /mnt/TreeCmp_v2.0-b76/bin/treeCmp.jar -r MATOPT/publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.collapsed.25_samples.nwk -d rf mc tt ms -i MATOPT/25_samples.opt.pb.nwk -o MATOPT_TREECMP_RESULTS/25_samples.opt.results
java -jar /mnt/TreeCmp_v2.0-b76/bin/treeCmp.jar -r MATOPT/publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.collapsed.26_samples.nwk -d rf mc tt ms -i MATOPT/26_samples.opt.pb.nwk -o MATOPT_TREECMP_RESULTS/26_samples.opt.results
java -jar /mnt/TreeCmp_v2.0-b76/bin/treeCmp.jar -r MATOPT/publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.collapsed.27_samples.nwk -d rf mc tt ms -i MATOPT/27_samples.opt.pb.nwk -o MATOPT_TREECMP_RESULTS/27_samples.opt.results
java -jar /mnt/TreeCmp_v2.0-b76/bin/treeCmp.jar -r MATOPT/publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.collapsed.28_samples.nwk -d rf mc tt ms -i MATOPT/28_samples.opt.pb.nwk -o MATOPT_TREECMP_RESULTS/28_samples.opt.results
java -jar /mnt/TreeCmp_v2.0-b76/bin/treeCmp.jar -r MATOPT/publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.collapsed.29_samples.nwk -d rf mc tt ms -i MATOPT/29_samples.opt.pb.nwk -o MATOPT_TREECMP_RESULTS/29_samples.opt.results
java -jar /mnt/TreeCmp_v2.0-b76/bin/treeCmp.jar -r MATOPT/publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.collapsed.30_samples.nwk -d rf mc tt ms -i MATOPT/30_samples.opt.pb.nwk -o MATOPT_TREECMP_RESULTS/30_samples.opt.results
java -jar /mnt/TreeCmp_v2.0-b76/bin/treeCmp.jar -r MATOPT/publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.collapsed.31_samples.nwk -d rf mc tt ms -i MATOPT/31_samples.opt.pb.nwk -o MATOPT_TREECMP_RESULTS/31_samples.opt.results
java -jar /mnt/TreeCmp_v2.0-b76/bin/treeCmp.jar -r MATOPT/publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.collapsed.32_samples.nwk -d rf mc tt ms -i MATOPT/32_samples.opt.pb.nwk -o MATOPT_TREECMP_RESULTS/32_samples.opt.results
java -jar /mnt/TreeCmp_v2.0-b76/bin/treeCmp.jar -r MATOPT/publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.collapsed.33_samples.nwk -d rf mc tt ms -i MATOPT/33_samples.opt.pb.nwk -o MATOPT_TREECMP_RESULTS/33_samples.opt.results
java -jar /mnt/TreeCmp_v2.0-b76/bin/treeCmp.jar -r MATOPT/publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.collapsed.34_samples.nwk -d rf mc tt ms -i MATOPT/34_samples.opt.pb.nwk -o MATOPT_TREECMP_RESULTS/34_samples.opt.results
java -jar /mnt/TreeCmp_v2.0-b76/bin/treeCmp.jar -r MATOPT/publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.collapsed.35_samples.nwk -d rf mc tt ms -i MATOPT/35_samples.opt.pb.nwk -o MATOPT_TREECMP_RESULTS/35_samples.opt.results
java -jar /mnt/TreeCmp_v2.0-b76/bin/treeCmp.jar -r MATOPT/publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.collapsed.36_samples.nwk -d rf mc tt ms -i MATOPT/36_samples.opt.pb.nwk -o MATOPT_TREECMP_RESULTS/36_samples.opt.results
java -jar /mnt/TreeCmp_v2.0-b76/bin/treeCmp.jar -r MATOPT/publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.collapsed.37_samples.nwk -d rf mc tt ms -i MATOPT/37_samples.opt.pb.nwk -o MATOPT_TREECMP_RESULTS/37_samples.opt.results
java -jar /mnt/TreeCmp_v2.0-b76/bin/treeCmp.jar -r MATOPT/publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.collapsed.38_samples.nwk -d rf mc tt ms -i MATOPT/38_samples.opt.pb.nwk -o MATOPT_TREECMP_RESULTS/38_samples.opt.results
java -jar /mnt/TreeCmp_v2.0-b76/bin/treeCmp.jar -r MATOPT/publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.collapsed.39_samples.nwk -d rf mc tt ms -i MATOPT/39_samples.opt.pb.nwk -o MATOPT_TREECMP_RESULTS/39_samples.opt.results
java -jar /mnt/TreeCmp_v2.0-b76/bin/treeCmp.jar -r MATOPT/publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.collapsed.40_samples.nwk -d rf mc tt ms -i MATOPT/40_samples.opt.pb.nwk -o MATOPT_TREECMP_RESULTS/40_samples.opt.results
java -jar /mnt/TreeCmp_v2.0-b76/bin/treeCmp.jar -r MATOPT/publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.collapsed.41_samples.nwk -d rf mc tt ms -i MATOPT/41_samples.opt.pb.nwk -o MATOPT_TREECMP_RESULTS/41_samples.opt.results
java -jar /mnt/TreeCmp_v2.0-b76/bin/treeCmp.jar -r MATOPT/publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.collapsed.42_samples.nwk -d rf mc tt ms -i MATOPT/42_samples.opt.pb.nwk -o MATOPT_TREECMP_RESULTS/42_samples.opt.results
java -jar /mnt/TreeCmp_v2.0-b76/bin/treeCmp.jar -r MATOPT/publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.collapsed.43_samples.nwk -d rf mc tt ms -i MATOPT/43_samples.opt.pb.nwk -o MATOPT_TREECMP_RESULTS/43_samples.opt.results
java -jar /mnt/TreeCmp_v2.0-b76/bin/treeCmp.jar -r MATOPT/publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.collapsed.44_samples.nwk -d rf mc tt ms -i MATOPT/44_samples.opt.pb.nwk -o MATOPT_TREECMP_RESULTS/44_samples.opt.results
java -jar /mnt/TreeCmp_v2.0-b76/bin/treeCmp.jar -r MATOPT/publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.collapsed.45_samples.nwk -d rf mc tt ms -i MATOPT/45_samples.opt.pb.nwk -o MATOPT_TREECMP_RESULTS/45_samples.opt.results
java -jar /mnt/TreeCmp_v2.0-b76/bin/treeCmp.jar -r MATOPT/publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.collapsed.46_samples.nwk -d rf mc tt ms -i MATOPT/46_samples.opt.pb.nwk -o MATOPT_TREECMP_RESULTS/46_samples.opt.results
java -jar /mnt/TreeCmp_v2.0-b76/bin/treeCmp.jar -r MATOPT/publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.collapsed.47_samples.nwk -d rf mc tt ms -i MATOPT/47_samples.opt.pb.nwk -o MATOPT_TREECMP_RESULTS/47_samples.opt.results
java -jar /mnt/TreeCmp_v2.0-b76/bin/treeCmp.jar -r MATOPT/publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.collapsed.48_samples.nwk -d rf mc tt ms -i MATOPT/48_samples.opt.pb.nwk -o MATOPT_TREECMP_RESULTS/48_samples.opt.results
java -jar /mnt/TreeCmp_v2.0-b76/bin/treeCmp.jar -r MATOPT/publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.collapsed.49_samples.nwk -d rf mc tt ms -i MATOPT/49_samples.opt.pb.nwk -o MATOPT_TREECMP_RESULTS/49_samples.opt.results
java -jar /mnt/TreeCmp_v2.0-b76/bin/treeCmp.jar -r MATOPT/publicMsa.2021-03-18.masked.retain_samples.save.minus_parsimony.collapsed.50_samples.nwk -d rf mc tt ms -i MATOPT/50_samples.opt.pb.nwk -o MATOPT_TREECMP_RESULTS/50_samples.opt.results