library(ape)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_1.nwk"))
t2 = unroot(read.tree("/mnt/SIM_USHER/IQ/1_samples.ml.iqtree.opt.condensed.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_2.nwk"))
t2 = unroot(read.tree("/mnt/SIM_USHER/IQ/2_samples.ml.iqtree.opt.condensed.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_3.nwk"))
t2 = unroot(read.tree("/mnt/SIM_USHER/IQ/3_samples.ml.iqtree.opt.condensed.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_4.nwk"))
t2 = unroot(read.tree("/mnt/SIM_USHER/IQ/4_samples.ml.iqtree.opt.condensed.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_5.nwk"))
t2 = unroot(read.tree("/mnt/SIM_USHER/IQ/5_samples.ml.iqtree.opt.condensed.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_6.nwk"))
t2 = unroot(read.tree("/mnt/SIM_USHER/IQ/6_samples.ml.iqtree.opt.condensed.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_7.nwk"))
t2 = unroot(read.tree("/mnt/SIM_USHER/IQ/7_samples.ml.iqtree.opt.condensed.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_8.nwk"))
t2 = unroot(read.tree("/mnt/SIM_USHER/IQ/8_samples.ml.iqtree.opt.condensed.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_9.nwk"))
t2 = unroot(read.tree("/mnt/SIM_USHER/IQ/9_samples.ml.iqtree.opt.condensed.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_10.nwk"))
t2 = unroot(read.tree("/mnt/SIM_USHER/IQ/10_samples.ml.iqtree.opt.condensed.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_11.nwk"))
t2 = unroot(read.tree("/mnt/SIM_USHER/IQ/11_samples.ml.iqtree.opt.condensed.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_12.nwk"))
t2 = unroot(read.tree("/mnt/SIM_USHER/IQ/12_samples.ml.iqtree.opt.condensed.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_13.nwk"))
t2 = unroot(read.tree("/mnt/SIM_USHER/IQ/13_samples.ml.iqtree.opt.condensed.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_14.nwk"))
t2 = unroot(read.tree("/mnt/SIM_USHER/IQ/14_samples.ml.iqtree.opt.condensed.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_15.nwk"))
t2 = unroot(read.tree("/mnt/SIM_USHER/IQ/15_samples.ml.iqtree.opt.condensed.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_16.nwk"))
t2 = unroot(read.tree("/mnt/SIM_USHER/IQ/16_samples.ml.iqtree.opt.condensed.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_17.nwk"))
t2 = unroot(read.tree("/mnt/SIM_USHER/IQ/17_samples.ml.iqtree.opt.condensed.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_18.nwk"))
t2 = unroot(read.tree("/mnt/SIM_USHER/IQ/18_samples.ml.iqtree.opt.condensed.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_19.nwk"))
t2 = unroot(read.tree("/mnt/SIM_USHER/IQ/19_samples.ml.iqtree.opt.condensed.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_20.nwk"))
t2 = unroot(read.tree("/mnt/SIM_USHER/IQ/20_samples.ml.iqtree.opt.condensed.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_21.nwk"))
t2 = unroot(read.tree("/mnt/SIM_USHER/IQ/21_samples.ml.iqtree.opt.condensed.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_22.nwk"))
t2 = unroot(read.tree("/mnt/SIM_USHER/IQ/22_samples.ml.iqtree.opt.condensed.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_23.nwk"))
t2 = unroot(read.tree("/mnt/SIM_USHER/IQ/23_samples.ml.iqtree.opt.condensed.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_24.nwk"))
t2 = unroot(read.tree("/mnt/SIM_USHER/IQ/24_samples.ml.iqtree.opt.condensed.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_25.nwk"))
t2 = unroot(read.tree("/mnt/SIM_USHER/IQ/25_samples.ml.iqtree.opt.condensed.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_26.nwk"))
t2 = unroot(read.tree("/mnt/SIM_USHER/IQ/26_samples.ml.iqtree.opt.condensed.nwk"))
dist.topo(t1,t2)
