library(ape)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_1.nwk"))
t2 = unroot(read.tree("1_samples.ml.fasttree.gtrg.opt.condensed.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_2.nwk"))
t2 = unroot(read.tree("2_samples.ml.fasttree.gtrg.opt.condensed.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_3.nwk"))
t2 = unroot(read.tree("3_samples.ml.fasttree.gtrg.opt.condensed.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_4.nwk"))
t2 = unroot(read.tree("4_samples.ml.fasttree.gtrg.opt.condensed.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_5.nwk"))
t2 = unroot(read.tree("5_samples.ml.fasttree.gtrg.opt.condensed.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_6.nwk"))
t2 = unroot(read.tree("6_samples.ml.fasttree.gtrg.opt.condensed.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_7.nwk"))
t2 = unroot(read.tree("7_samples.ml.fasttree.gtrg.opt.condensed.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_8.nwk"))
t2 = unroot(read.tree("8_samples.ml.fasttree.gtrg.opt.condensed.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_9.nwk"))
t2 = unroot(read.tree("9_samples.ml.fasttree.gtrg.opt.condensed.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_10.nwk"))
t2 = unroot(read.tree("10_samples.ml.fasttree.gtrg.opt.condensed.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_11.nwk"))
t2 = unroot(read.tree("11_samples.ml.fasttree.gtrg.opt.condensed.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_12.nwk"))
t2 = unroot(read.tree("12_samples.ml.fasttree.gtrg.opt.condensed.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_13.nwk"))
t2 = unroot(read.tree("13_samples.ml.fasttree.gtrg.opt.condensed.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_14.nwk"))
t2 = unroot(read.tree("14_samples.ml.fasttree.gtrg.opt.condensed.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_15.nwk"))
t2 = unroot(read.tree("15_samples.ml.fasttree.gtrg.opt.condensed.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_16.nwk"))
t2 = unroot(read.tree("16_samples.ml.fasttree.gtrg.opt.condensed.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_17.nwk"))
t2 = unroot(read.tree("17_samples.ml.fasttree.gtrg.opt.condensed.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_18.nwk"))
t2 = unroot(read.tree("18_samples.ml.fasttree.gtrg.opt.condensed.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_19.nwk"))
t2 = unroot(read.tree("19_samples.ml.fasttree.gtrg.opt.condensed.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_20.nwk"))
t2 = unroot(read.tree("20_samples.ml.fasttree.gtrg.opt.condensed.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_21.nwk"))
t2 = unroot(read.tree("21_samples.ml.fasttree.gtrg.opt.condensed.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_22.nwk"))
t2 = unroot(read.tree("22_samples.ml.fasttree.gtrg.opt.condensed.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_23.nwk"))
t2 = unroot(read.tree("23_samples.ml.fasttree.gtrg.opt.condensed.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_24.nwk"))
t2 = unroot(read.tree("24_samples.ml.fasttree.gtrg.opt.condensed.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_25.nwk"))
t2 = unroot(read.tree("25_samples.ml.fasttree.gtrg.opt.condensed.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_26.nwk"))
t2 = unroot(read.tree("26_samples.ml.fasttree.gtrg.opt.condensed.nwk"))
dist.topo(t1,t2)
