library(ape)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_1.nwk"))
t2 = unroot(read.tree("1.opt.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_2.nwk"))
t2 = unroot(read.tree("2.opt.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_3.nwk"))
t2 = unroot(read.tree("3.opt.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_4.nwk"))
t2 = unroot(read.tree("4.opt.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_5.nwk"))
t2 = unroot(read.tree("5.opt.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_6.nwk"))
t2 = unroot(read.tree("6.opt.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_7.nwk"))
t2 = unroot(read.tree("7.opt.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_8.nwk"))
t2 = unroot(read.tree("8.opt.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_9.nwk"))
t2 = unroot(read.tree("9.opt.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_10.nwk"))
t2 = unroot(read.tree("10.opt.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_11.nwk"))
t2 = unroot(read.tree("11.opt.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_12.nwk"))
t2 = unroot(read.tree("12.opt.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_13.nwk"))
t2 = unroot(read.tree("13.opt.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_14.nwk"))
t2 = unroot(read.tree("14.opt.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_15.nwk"))
t2 = unroot(read.tree("15.opt.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_16.nwk"))
t2 = unroot(read.tree("16.opt.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_17.nwk"))
t2 = unroot(read.tree("17.opt.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_18.nwk"))
t2 = unroot(read.tree("18.opt.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_19.nwk"))
t2 = unroot(read.tree("19.opt.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_20.nwk"))
t2 = unroot(read.tree("20.opt.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_21.nwk"))
t2 = unroot(read.tree("21.opt.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_22.nwk"))
t2 = unroot(read.tree("22.opt.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_23.nwk"))
t2 = unroot(read.tree("23.opt.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_24.nwk"))
t2 = unroot(read.tree("24.opt.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_25.nwk"))
t2 = unroot(read.tree("25.opt.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_26.nwk"))
t2 = unroot(read.tree("26.opt.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_27.nwk"))
t2 = unroot(read.tree("27.opt.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_28.nwk"))
t2 = unroot(read.tree("28.opt.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_29.nwk"))
t2 = unroot(read.tree("29.opt.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_30.nwk"))
t2 = unroot(read.tree("30.opt.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_31.nwk"))
t2 = unroot(read.tree("31.opt.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_32.nwk"))
t2 = unroot(read.tree("32.opt.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_33.nwk"))
t2 = unroot(read.tree("33.opt.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_34.nwk"))
t2 = unroot(read.tree("34.opt.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_35.nwk"))
t2 = unroot(read.tree("35.opt.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_36.nwk"))
t2 = unroot(read.tree("36.opt.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_37.nwk"))
t2 = unroot(read.tree("37.opt.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_38.nwk"))
t2 = unroot(read.tree("38.opt.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_39.nwk"))
t2 = unroot(read.tree("39.opt.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_40.nwk"))
t2 = unroot(read.tree("40.opt.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_41.nwk"))
t2 = unroot(read.tree("41.opt.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_42.nwk"))
t2 = unroot(read.tree("42.opt.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_43.nwk"))
t2 = unroot(read.tree("43.opt.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_44.nwk"))
t2 = unroot(read.tree("44.opt.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_45.nwk"))
t2 = unroot(read.tree("45.opt.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_46.nwk"))
t2 = unroot(read.tree("46.opt.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_47.nwk"))
t2 = unroot(read.tree("47.opt.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_48.nwk"))
t2 = unroot(read.tree("48.opt.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_49.nwk"))
t2 = unroot(read.tree("49.opt.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_50.nwk"))
t2 = unroot(read.tree("50.opt.nwk"))
dist.topo(t1,t2)
