library(ape)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_1.nwk"))
t2 = unroot(read.tree("1.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_2.nwk"))
t2 = unroot(read.tree("2.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_3.nwk"))
t2 = unroot(read.tree("3.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_4.nwk"))
t2 = unroot(read.tree("4.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_5.nwk"))
t2 = unroot(read.tree("5.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_6.nwk"))
t2 = unroot(read.tree("6.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_7.nwk"))
t2 = unroot(read.tree("7.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_8.nwk"))
t2 = unroot(read.tree("8.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_9.nwk"))
t2 = unroot(read.tree("9.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_10.nwk"))
t2 = unroot(read.tree("10.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_11.nwk"))
t2 = unroot(read.tree("11.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_12.nwk"))
t2 = unroot(read.tree("12.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_13.nwk"))
t2 = unroot(read.tree("13.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_14.nwk"))
t2 = unroot(read.tree("14.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_15.nwk"))
t2 = unroot(read.tree("15.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_16.nwk"))
t2 = unroot(read.tree("16.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_17.nwk"))
t2 = unroot(read.tree("17.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_18.nwk"))
t2 = unroot(read.tree("18.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_19.nwk"))
t2 = unroot(read.tree("19.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_20.nwk"))
t2 = unroot(read.tree("20.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_21.nwk"))
t2 = unroot(read.tree("21.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_22.nwk"))
t2 = unroot(read.tree("22.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_23.nwk"))
t2 = unroot(read.tree("23.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_24.nwk"))
t2 = unroot(read.tree("24.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_25.nwk"))
t2 = unroot(read.tree("25.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_26.nwk"))
t2 = unroot(read.tree("26.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_27.nwk"))
t2 = unroot(read.tree("27.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_28.nwk"))
t2 = unroot(read.tree("28.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_29.nwk"))
t2 = unroot(read.tree("29.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_30.nwk"))
t2 = unroot(read.tree("30.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_31.nwk"))
t2 = unroot(read.tree("31.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_32.nwk"))
t2 = unroot(read.tree("32.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_33.nwk"))
t2 = unroot(read.tree("33.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_34.nwk"))
t2 = unroot(read.tree("34.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_35.nwk"))
t2 = unroot(read.tree("35.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_36.nwk"))
t2 = unroot(read.tree("36.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_37.nwk"))
t2 = unroot(read.tree("37.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_38.nwk"))
t2 = unroot(read.tree("38.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_39.nwk"))
t2 = unroot(read.tree("39.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_40.nwk"))
t2 = unroot(read.tree("40.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_41.nwk"))
t2 = unroot(read.tree("41.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_42.nwk"))
t2 = unroot(read.tree("42.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_43.nwk"))
t2 = unroot(read.tree("43.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_44.nwk"))
t2 = unroot(read.tree("44.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_45.nwk"))
t2 = unroot(read.tree("45.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_46.nwk"))
t2 = unroot(read.tree("46.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_47.nwk"))
t2 = unroot(read.tree("47.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_48.nwk"))
t2 = unroot(read.tree("48.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_49.nwk"))
t2 = unroot(read.tree("49.nwk"))
dist.topo(t1,t2)
t1 = unroot(read.tree("/mnt/SIM_USHER/GROUND_TRUTH_NEWICKS/STARTING_GROUND_TRUTH_TREE_PRUNED_50.nwk"))
t2 = unroot(read.tree("50.nwk"))
dist.topo(t1,t2)
